name: CI build
on:
  push:
    branches:
    - master
    - godot4-meson
  pull_request:
    branches:
    - master
    - godot4-meson


# Global Settings
env:
  PYTHON_VERSION: "3.8"  # Python to run the build, no the one shipped !


jobs:


  static-checks:
    name: '📊 Static checks'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f1d3225b5376a0791fdee5a0e8eac5289355e43a  # pin@v2
        with:
            submodules: true
      - name: Set up Python
        uses: actions/setup-python@0291cefc54fa79cd1986aee8fa5ecb89ad4defea  # pin@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Bootstrap
        run: |
          set -eux
          python --version
          pip install pre-commit
      - name: Pre-commit hooks check
        run: |
          pre-commit run --all-files --show-diff-on-failure


#################################################################################


  linux-build:
    name: '🐧 Linux build'
    runs-on: ubuntu-latest
    env:
      CC: clang
      LD: lld
      PLATFORM: linux-x86_64
    steps:
      - name: 'Checkout'
        uses: actions/checkout@f1d3225b5376a0791fdee5a0e8eac5289355e43a  # pin@v2
        with:
            submodules: true
      - name: 'Set up Python'
        uses: actions/setup-python@0291cefc54fa79cd1986aee8fa5ecb89ad4defea  # pin@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: 'Setup venv'
        run: |
          set -eux
          ${{ env.CC }} --version
          python --version
          pip install -U pip
          pip install -r requirements.in
      - name: 'Setup project'
        run: |
          set -eux
          python .github/scripts/meson_setup_or_dump_log.py build/
      - name: 'Build project'
        run: |
          set -eux
          meson compile -C build/
      - name: 'Run tests'
        run: |
          set -eux
          python tests/run.py helloworld \
            --build-dir build/ \
            -- --display-driver headless
      # - name: 'Generate artifact archive'
      #   run: |
      #     set -eux
      #     meson compile -C build/ release
      # - name: 'Export release artifact'
      #   uses: actions/upload-artifact@11830c9f4d30053679cb8904e3b3ce1b8c00bf40  # pin@v2
      #   with:
      #     name: ${{ env.PLATFORM }}-release
      #     path: 'build/godot-python-*.tar.bz2'


#################################################################################


  windows-build:
    name: '🏁 Windows build'
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - PLATFORM: 'windows-x86_64'
            PYTHON_ARCH: 'x64'
            MSVC_ARCH: 'x64'
          - PLATFORM: 'windows-x86'
            PYTHON_ARCH: 'x86'
            MSVC_ARCH: 'x86'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@f1d3225b5376a0791fdee5a0e8eac5289355e43a  # pin@v2
        with:
            submodules: true
      - name: 'Set up MSVC'
        uses: egor-tensin/vs-shell@9a932a62d05192eae18ca370155cf877eecc2202  # pin@v2.1
        with:
          arch: ${{ matrix.MSVC_ARCH }}
      - name: 'Set up Python'
        uses: actions/setup-python@0291cefc54fa79cd1986aee8fa5ecb89ad4defea  # pin@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          architecture: ${{ matrix.PYTHON_ARCH }}
      - name: 'Setup venv'
        shell: bash
        run: |
          set -eux
          python --version
          pip install -U pip
          pip install -r requirements.in
      - name: 'Setup project'
        run: |
          python .github/scripts/meson_setup_or_dump_log.py build/
      - name: 'Build project'
        run: |
          meson compile -C build/
      # - name: 'Run tests'
      #   run: |
      #     python tests/run.py helloworld \
      #       --build-dir build/ \
      #       -- --display-driver headless
      # - name: 'Install Mesa3D OpenGL'
      #   shell: bash
      #   run: |
      #     set -eux
      #     # Azure pipelines doesn't provide a GPU with an OpenGL driver,
      #     # hence we use Mesa3D as software OpenGL driver
      #     pushd build/${{ matrix.PLATFORM }}/platforms/
      #     if [ "${{ matrix.PLATFORM }}" = "windows-64" ]
      #     then
      #       curl https://downloads.fdossena.com/Projects/Mesa3D/Builds/MesaForWindows-x64-20.0.7.7z -o mesa.7z
      #     else
      #       curl https://downloads.fdossena.com/Projects/Mesa3D/Builds/MesaForWindows-20.0.7.7z -o mesa.7z
      #     fi
      #     # opengl32.dll must be extracted in the same directory than Godot binary
      #     7z.exe x mesa.7z
      #     ls -lh opengl32.dll  # Sanity check
      #     popd
      # - name: 'Run tests'
      #   shell: bash
      #   run: |
      #     set -eux
      #     python tests/run.py --build-dir build/ --godot-binary ${{ GODOT_BINARY_VERSION }}
      # - name: 'Generate artifact archive'
      #   shell: bash
      #   run: |
      #     scons release
      # - name: 'Export release artifact'
      #   uses: actions/upload-artifact@11830c9f4d30053679cb8904e3b3ce1b8c00bf40  # pin@v2
      #   with:
      #     name: ${{ matrix.PLATFORM }}-release
      #     path: 'build/godot-python-*.zip'


#################################################################################


  macos-build:
    name: '🍎 macOS build'
    runs-on: macos-latest
    env:
      CC: clang
      LD: lld
      PLATFORM: 'macos-x86_64'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@f1d3225b5376a0791fdee5a0e8eac5289355e43a  # pin@v2
        with:
            submodules: true
      - name: 'Set up Python'
        uses: actions/setup-python@0291cefc54fa79cd1986aee8fa5ecb89ad4defea  # pin@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: 'Setup venv'
        run: |
          set -eux
          ${{ env.CC }} --version
          python --version
          pip install -U pip
          pip install -r requirements.txt
      - name: 'Setup project'
        run: |
          set -eux
          python .github/scripts/meson_setup_or_dump_log.py build/
      - name: 'Build project'
        run: |
          set -eux
          meson compile -C build/
      # TODO: see https://github.com/touilleMan/godot-python/issues/358
      # - name: 'Run tests'
      #   run: |
      #     set -eux
      #     python tests/run.py helloworld \
      #       --build-dir build/ \
      #       -- --display-driver headless
      # - name: 'Generate artifact archive'
      #   run: |
      #     set -eux
      #     meson compile -C build/ release
      # - name: 'Export release artifact'
      #   uses: actions/upload-artifact@11830c9f4d30053679cb8904e3b3ce1b8c00bf40  # pin@v2
      #   with:
      #     name: ${{ env.PLATFORM }}-release
      #     path: 'build/godot-python-*.tar.bz2'


#################################################################################


#  publish-release:
#    name: 'Publish ${{ matrix.PLATFORM }} release'
#    if: startsWith(github.ref, 'refs/tags/v')
#    runs-on: ubuntu-latest
#    needs:
#      - linux-build
#      - windows-build
#      - macos-build
#    strategy:
#      matrix:
#        include:
#          - PLATFORM: linux-x86_64
#          - PLATFORM: windows-x86_64
#          - PLATFORM: windows-x86
#          - PLATFORM: osx-x86_64
#    steps:
#      - uses: actions/download-artifact@0ede0875b5db9a2824878bbbbe3d758a75eb8268  # pin@v2
#        name: ${{ matrix.PLATFORM }}-release
#      - name: 'Upload release'
#        uses: svenstaro/upload-release-action@483c1e56f95e88835747b1c7c60581215016cbf2  # pin@v2
#        with:
#          repo_token: ${{ secrets.GITHUB_TOKEN }}
#          tag: ${{ github.ref }}
#          file: godot-python-*.*
#          file_glob: true
#          overwrite: true
